services:
  web:
    build:
      context: ./docker/apache
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/umentor:/var/www/html
    networks:
      - appnet

  db:
    image: mariadb:10.6.14
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: umentor
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge
